### ISSUE TITLE
Compilation error in Array pattern matching in Twirl 1.4.1

### ISSUE THREAD

**Issue by takezoe** [playframework/twirl#222]
The following template have worked in Twirl 1.3.15.
```
@defining(content.split(":")){ case Array(head, rest @ _*) =>
  ...
}
```
But it fails to compile with `Expected '}' but found '@'` in Twirl 1.4.1.

**Comment by takezoe** [comment]
This works:
```
@defining(content.split(":")){ case Array(head, rest @ _*) => {
  ...
}}
```
Is this intended change?

**Comment by mkurz** [comment]
Yes, kind of intended, that's a result of #192 and #194. We might want to add this to the Play Framework migration notes however.

**Comment by takezoe** [comment]
I see. Thanks.

> We might want to add this to the Play Framework migration notes however.

This change will break a lot of Twirl based Play applications. So describing in Play's migration notes would help Play users.

**Comment by takezoe** [comment]
JFYI: I needed the following changes to migrate Twirl 1.3.x to 1.4.x:
https://github.com/gitbucket/gitbucket/pull/2320/files

**Comment by ignasi35** [comment]
thanks for reporting @takezoe . Raised https://github.com/playframework/playframework/issues/9411
